version: "3.9"
services:
  php:
    # image: mmonstar/mmon-lara-app-xdebug:1.1
    build: ./php-fpm
    container_name: laravel-php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laranet

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 2080:80
      - 2443:443
    volumes:
      - ./src/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laranet

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rupi@@1234
      - MYSQL_DATABASE=rupi_db
      - MYSQL_USER=rupi
      - MYSQL_PASSWORD=rupi@@1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    networks:
      - laranet

  redis:
    image: redis:alpine
    restart: unless-stopped
    labels:
      - "name=redis"
      - "mode=standalone"
    # volumes:
    # - ./redis/data:/data
    # - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    # command: redis-server /usr/local/conf/redis.conf
    command: redis-server --port 6379
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
